### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: diningroom_train
eval_dataset: diningroom_test
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen_coder_diningroom/lora/sft2
logging_steps: 10
save_steps: 150
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 150.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### report
report_to: wandb
run_name: layout_html_diningroom

### eval
# val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 30
predict_with_generate: true
do_predict: true
