data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_desc_sgdiffusion"
    augmentations: ["fixed_rotation"]
    dataset_directory: "dataset/InstructScene/threed_front_bedroom"
    annotation_file: "configs/bedroom_threed_front_splits.csv"
    path_to_invalid_scene_ids: "configs/invalid_threed_front_rooms.txt"
    path_to_invalid_bbox_jids: "configs/black_list.txt"
    path_to_floor_plan_textures: "configs/floor_plan_texture_images"
    path_to_pickled_3d_futute_models: "dataset/InstructScene/threed_future_model_bedroom.pkl"
    filter_fn: "threed_front_bedroom"
    train_stats: "dataset_stats.txt"
    room_layout_size: "64,64"
    max_length: 12

model:
    name: "vq_objfeat_sg_gtf"
    text_encoder: "openai/clip-vit-base-patch32"

training:
    splits: ["train", "val"]
    epochs: 2000
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 10
    log_frequency: 1
    optimizer:
        name: "adamw"
        lr: 0.0001
        weight_decay: 0.02
    loss_weights:
        vb_x: 1.
        vb_e: 1.
    ema:
        use_ema: true
        max_decay: 0.9999
        min_decay: 0.
        update_after_step: 0
        use_warmup: true
        inv_gamma: 1.
        power: 0.75

validation:
    splits: ["test"]
    batch_size: 256
    frequency: 1
